//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/OpticalLayer.msg.
//

#ifndef _OPTICALLAYER_M_H_
#define _OPTICALLAYER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/OpticalLayer.msg</tt> by opp_msgc.
 * <pre>
 * packet OpticalLayer {
 *     int wavelengthNo;
 * }
 * </pre>
 */
class OpticalLayer : public ::cPacket
{
  protected:
    int wavelengthNo_var;

  private:
    void copy(const OpticalLayer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OpticalLayer&);

  public:
    OpticalLayer(const char *name=NULL, int kind=0);
    OpticalLayer(const OpticalLayer& other);
    virtual ~OpticalLayer();
    OpticalLayer& operator=(const OpticalLayer& other);
    virtual OpticalLayer *dup() const {return new OpticalLayer(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getWavelengthNo() const;
    virtual void setWavelengthNo(int wavelengthNo);
};

inline void doPacking(cCommBuffer *b, OpticalLayer& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OpticalLayer& obj) {obj.parsimUnpack(b);}


#endif // _OPTICALLAYER_M_H_
